print("=== ElectricCar ===")
let tesla = ElectricCar(brand: "Tesla", model: "Model S", year: "2025", engine: ElectricEngine())
tesla.drive()
tesla.stop()
tesla.supply()

print("=== HybridCar ===")
let toyota = HybridCar(brand: "Toyota", model: "Prius", year: "2025", engine: HydrogenEngine())
toyota.drive()
toyota.stop()
toyota.supply()
toyota.switchEngine(to: ElectricEngine())
toyota.supply()
